[2025-02-01T20:32:21.874+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T20:32:21.895+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_taxi_ingestion.process_and_insert_to_db scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2025-02-01T20:32:21.908+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_taxi_ingestion.process_and_insert_to_db scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2025-02-01T20:32:21.909+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T20:32:21.925+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_and_insert_to_db> on 2021-03-02 06:00:00+00:00
[2025-02-01T20:32:21.935+0000] {standard_task_runner.py:72} INFO - Started process 2601 to run task
[2025-02-01T20:32:21.938+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_ingestion', 'process_and_insert_to_db', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpa0je6onr']
[2025-02-01T20:32:21.942+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask process_and_insert_to_db
[2025-02-01T20:32:22.024+0000] {task_command.py:467} INFO - Running <TaskInstance: yellow_taxi_ingestion.process_and_insert_to_db scheduled__2021-03-02T06:00:00+00:00 [running]> on host d835a1784a00
[2025-02-01T20:32:22.159+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_taxi_ingestion' AIRFLOW_CTX_TASK_ID='process_and_insert_to_db' AIRFLOW_CTX_EXECUTION_DATE='2021-03-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-03-02T06:00:00+00:00'
[2025-02-01T20:32:22.161+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T20:32:22.178+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_ingestion_local.py", line 43, in process_and_insert_to_db
    df_iter = pd.read_csv(csv_name, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'output_2021_03.csv'
[2025-02-01T20:32:22.197+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=yellow_taxi_ingestion, task_id=process_and_insert_to_db, run_id=scheduled__2021-03-02T06:00:00+00:00, execution_date=20210302T060000, start_date=20250201T203221, end_date=20250201T203222
[2025-02-01T20:32:22.216+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T20:32:22.217+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task process_and_insert_to_db ([Errno 2] No such file or directory: 'output_2021_03.csv'; 2601)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/data_ingestion_local.py", line 43, in process_and_insert_to_db
    df_iter = pd.read_csv(csv_name, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'output_2021_03.csv'
[2025-02-01T20:32:22.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-01T20:32:22.252+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T20:32:22.255+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
