[2025-04-07T19:42:43.256+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-07T19:42:43.292+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: GCP_ingestion_green.create_temp_table scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2025-04-07T19:42:43.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: GCP_ingestion_green.create_temp_table scheduled__2019-02-02T06:00:00+00:00 [queued]>
[2025-04-07T19:42:43.312+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-04-07T19:42:43.331+0000] {taskinstance.py:2889} INFO - Executing <Task(BigQueryInsertJobOperator): create_temp_table> on 2019-02-02 06:00:00+00:00
[2025-04-07T19:42:43.342+0000] {standard_task_runner.py:72} INFO - Started process 1962 to run task
[2025-04-07T19:42:43.346+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'GCP_ingestion_green', 'create_temp_table', 'scheduled__2019-02-02T06:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcp_green.py', '--cfg-path', '/tmp/tmpmyvj_ovn']
[2025-04-07T19:42:43.348+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask create_temp_table
[2025-04-07T19:42:43.406+0000] {task_command.py:467} INFO - Running <TaskInstance: GCP_ingestion_green.create_temp_table scheduled__2019-02-02T06:00:00+00:00 [running]> on host ca240955ca52
[2025-04-07T19:42:43.902+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='GCP_ingestion_green' AIRFLOW_CTX_TASK_ID='create_temp_table' AIRFLOW_CTX_EXECUTION_DATE='2019-02-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-02-02T06:00:00+00:00'
[2025-04-07T19:42:43.903+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-07T19:42:43.928+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-07T19:42:43.937+0000] {base.py:84} INFO - Retrieving connection 'gcp-***'
[2025-04-07T19:42:43.982+0000] {bigquery.py:2959} INFO - Executing: {'query': {'query': '\n                CREATE OR REPLACE TABLE `zoomcamp-***-456109.ny_taxi_data.green_taxi_2019_02_tmp`\n                AS\n                SELECT\n                    MD5(CONCAT(\n                        COALESCE(CAST(VendorID AS STRING), ""),\n                        COALESCE(CAST(lpep_pickup_datetime AS STRING), ""),\n                        COALESCE(CAST(lpep_dropoff_datetime AS STRING), ""),\n                        COALESCE(CAST(PULocationID AS STRING), ""),\n                        COALESCE(CAST(DOLocationID AS STRING), "")\n                    )) AS unique_row_id,\n                    "output_2019_02.parquet" AS filename,\n                    *\n                FROM `zoomcamp-***-456109.ny_taxi_data.green_taxi_2019_02_ext`;\n            ', 'useLegacySql': False}}'
[2025-04-07T19:42:43.985+0000] {bigquery.py:1699} INFO - Inserting job ***_GCP_ingestion_green_create_temp_table_2019_02_02T06_00_00_00_00_fa2fd5dab655d10a3e7273fa63a88adf
[2025-04-07T19:42:44.865+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 3025, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. zoomcamp-airflow-service@zoomcamp-airflow-456109.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist). Please make sure gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.; reason: accessDenied, location: gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet, message: Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. zoomcamp-airflow-service@zoomcamp-airflow-456109.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist). Please make sure gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.

Location: EU
Job ID: airflow_GCP_ingestion_green_create_temp_table_2019_02_02T06_00_00_00_00_fa2fd5dab655d10a3e7273fa63a88adf

[2025-04-07T19:42:44.883+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=GCP_ingestion_green, task_id=create_temp_table, run_id=scheduled__2019-02-02T06:00:00+00:00, execution_date=20190202T060000, start_date=20250407T194243, end_date=20250407T194244
[2025-04-07T19:42:44.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-07T19:42:44.910+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task create_temp_table (403 Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. zoomcamp-airflow-service@zoomcamp-airflow-456109.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist). Please make sure gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.; reason: accessDenied, location: gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet, message: Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. zoomcamp-airflow-service@zoomcamp-airflow-456109.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist). Please make sure gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.

Location: EU
Job ID: airflow_GCP_ingestion_green_create_temp_table_2019_02_02T06_00_00_00_00_fa2fd5dab655d10a3e7273fa63a88adf
; 1962)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 3025, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. zoomcamp-airflow-service@zoomcamp-airflow-456109.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist). Please make sure gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.; reason: accessDenied, location: gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet, message: Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern. zoomcamp-airflow-service@zoomcamp-airflow-456109.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist). Please make sure gs://zoomcamp-data-lake-jivago-2025/raw/output_2019_02.parquet is accessible via appropriate IAM roles, e.g. Storage Object Viewer or Storage Object Creator.

Location: EU
Job ID: airflow_GCP_ingestion_green_create_temp_table_2019_02_02T06_00_00_00_00_fa2fd5dab655d10a3e7273fa63a88adf

[2025-04-07T19:42:44.973+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-07T19:42:45.010+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-07T19:42:45.014+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
